lib/cookbook-release/git-utilities.rb, lib/cookbook-release/release.rb
Otherwise, version detection might not work properly when the :path
source type in berkshelf.
Fix #7
cc @aboten
=> Launch git command in the proper git repository

README.md, lib/cookbook-release.rb, lib/cookbook-release/release.rb, spec/release_spec.rb
- correct typo in default category
- allow to configure cookbook category through environment
- also fixed a bug where the error message would always be displayed
Fix #5
Fix #4 
cc @aboten
=> Make cookbook category configurable

lib/cookbook-release/git-utilities.rb
We use a magic separator that unlikely enough.
cc @aboten
=> Improve git commit one-line parsing

README.md, lib/cookbook-release/git-utilities.rb, lib/cookbook-release/release.rb, lib/cookbook-release/supermarket.rb
Fix #6 by adding environment variable to control ssl certificate validation on cookbook release.
Fix `missing to_version method` exception on `release!` task by setting up a local file with the latest version.
Fix & complete README.
=> Fix some release! task bug

lib/cookbook-release/git-utilities.rb
This message was relevant when we used to add a new commit on this
history
=> Adapt error message to remove "git reset --hard" advice

lib/cookbook-release/git-utilities.rb
Windows shell (aka batch) does not care about single quote :(
=> Use double quote in git command for windows shell

lib/cookbook-release/git-utilities.rb
We default to 0.1.0 and log a warning.
Fix #13
=> Boostrap correctly cookbook_version when no version tag can be found

lib/cookbook-release/git-utilities.rb
We don't want to check that we are in a git directory but (more strict)
that the cookbook dir is a independant repository.
Simply testing for .git/ existence seems sufficient
=> Make a simpler heuristic to detect if we are in a git directory

README.md, cookbook-release.gemspec, lib/cookbook-release.rb, lib/cookbook-release/changelog.rb, lib/cookbook-release/commit.rb, lib/cookbook-release/git-utilities.rb, spec/changelog_spec.rb, spec/git_spec.rb
This could be use to generate a changelog and enrich it with the major/risky information.
=> Add ability to publish a html changelog from git history

cookbook-release.gemspec, lib/cookbook-release/git-utilities.rb, lib/cookbook-release/release.rb, spec/release_spec.rb
For cookbook without any release, we start by version 0.1.0
Change-Id: I7f1f28026160af299daec520320190c9709fa62f
=> Allow bootstrap of cookbook without any release

lib/cookbook-release/git-utilities.rb, spec/git_spec.rb
Former tag matching was limiting major release to 9.
*Cc.* @aboten
=> Handle major release greater than 9

lib/cookbook-release/commit.rb, spec/changelog_spec.rb
Normal commits will still look like: *123456* _John Doe <j.doe@nobody.com>_ `hello`
Risky / breaking commits will look like: *654321* @j.doe `[Risky] hello`
Because of limited Markdown option for combining mention and other formatting options, there is a tradeoff on the way the mentioned author will appear.
=> Add a Slack mention of author on risky commits

lib/cookbook-release.rb, lib/cookbook-release/changelog.rb
Gives priority to risky/breaking commits and puts them on top of the output. Shows a full changelog below the riskies without details and a detailed changelog for riskies below everything.
=> Add rake tasks to print changelog by importance

lib/cookbook-release/release.rb
This will allow to relaunch 'rake release!' without failure when needed
Change-Id: Ib767c805e3e6cdd04c068626c6a5e416d81bcf2e
=> Allow silent fail

.travis.yml, README.md, cookbook-release.gemspec, lib/cookbook-release.rb, lib/cookbook-release/git-utilities.rb, spec/git_spec.rb
Currently the changelog takes the root of the git directory and looks
at all changes, regardless of the level. This patch takes the first
parameter and uses that for the `git log` command, if present. If
missing, it behaves as before
=> Add changelog directory parameter option

cookbook-release.gemspec, lib/cookbook-release/commit.rb, spec/commit_spec.rb, spec/git_spec.rb
This patch provide a markdown message that does not escape emojis.
It makes pasting such messages in slack (for instance) more readable
(which is the goal of providing such changelog)
Emojis in commits have become more present so it's natural to start
supporting them.
=> Properly un-escape emojis

lib/cookbook-release/changelog.rb, spec/changelog_spec.rb
THis section is less readable and we should instead show the only
commits we've not displayed so far: "nodes only" commits
Change-Id: I473e131b07568b0336d56b5bf8c16b50949cd739
=> Remove "full changelog" section

lib/cookbook-release/git-utilities.rb, lib/cookbook-release/release.rb, spec/git_spec.rb
In order for this lib to work in a monorepo setup, we need to support cookbooks in sub-directories and per-cookbook tag names.
With these changes we are able to tag a commit with a `cookbook-x.y.z` with level depending on changes in cookbook's directory only.
For instance, a `major` change to `cookbooks/cookbook_a` directory would give a `cookbook_a-2.0.0` tag.
=> Add support for multiple cookbooks in a single repository

lib/cookbook-release/git-utilities.rb, spec/git_spec.rb
Initial implementation could produce invalid result when the code is evaluated in a git directory which is not related with the cookbook.
For instance when berkshelf fetches cookbooks from git source it will checkout the code in a configured berkshelf_path directory and evaluate the metadata.rb of the cookbook.
If the configured berkshelf_path is inside a git directory, this will be considered as the "git root dir" of the cookbook and will mess up with the version computation.
This commit fixes the GitUtilities.find_root logic by quickly checking whether the given directory is tracked by git.
If the dir is not tracked or the command used to determine the tracking status just fail, it means it is not part of the parent git repository.
=> Fix git root directory discovery

cookbook-release.gemspec
With Chef 17, the knife code has been extracted to a dedicated gem.
=> This means that to be compatible with Chef 17 we should leverage the knife gem which only supports Chef 17.
As for now we want to be compatible with older Chef version we can't do that so easily.
The idea is to create a 1.6 branch which support Chef until version 17, and once stable [1], release a 2.0 version of cookbook release with only Chef 17 support.
[1] otherwise we'll have to backport fixes on 1.6 branch
=> Add constraint on Chef to not support version >= 17

lib/cookbook-release/git-utilities.rb, lib/cookbook-release/release.rb, lib/cookbook-release/supermarket.rb
Cookbook path was hardcoded to '.'; allow passing it as parameter to
#publish_ck, and use git sub_dir property to fill it.
=> Update supermarket push for mono-repo layout

cookbook-release.gemspec
git-ng fork has not been updated for 7 years, and requiring it here creates some conflicts where we expect to have the 'git' gem used and we instead get the 'git-ng' one.
Issue with utf-8 https://github.com/kamaradclimber/ruby-git/commit/5856b704007db12fb64f204ec42491992934f2f4 should be fine with upstream git updated code https://github.com/ruby-git/ruby-git/blob/dce68167840d2027832f321a9e0945b81e3b4cf7/lib/git/lib.rb#L1153
If not, worst case scenario is we do not have emojis in the commit messages...
=> use upstream git library instead of outdated fork
